# Generated by Django 5.2.7 on 2026-06-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le')),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
