# Generated by Django 5.2.7 on 2026-06-13 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro de commande')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('SHIPPING', 'En livraison'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=15, verbose_name='Statut')),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Montant total')),
                ('discount_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Remise')),
                ('final_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Montant final')),
                ('shipping_address', models.TextField(verbose_name='Adresse de livraison')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='Téléphone de livraison')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promotions.promocode', verbose_name='Code promo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('product_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix unitaire')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('subtotal', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Sous-total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Commande')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
    ]
