# Generated by Django 5.2.7 on 2026-06-13 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pourcentage de remise')),
                ('min_order_amount', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Montant minimum')),
                ('max_uses', models.PositiveIntegerField(default=0, verbose_name='Utilisations max (0=illimité)')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Utilisations')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_codes', to='products.category', verbose_name='Catégorie (optionnel)')),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
                'ordering': ['-created_at'],
            },
        ),
    ]
